Script started on 2023-05-09 18:59:18-07:00 [TERM="xterm-256color" TTY="/dev/pts/686" COLUMNS="108" LINES="32"]
alias ll='ls -l --color=auto'
bash: alias: =: not found
bash: alias: ls -l: not found
[?2004h[vyamang@cancun HW4]$ [7mecho $USER[27mecho $USER
[?2004l
vyamang
[?2004h[vyamang@cancun HW4]$ [7mexport PATH=$PATH:.[27m

[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cexport PATH=$PATH:.

[A
[?2004l
[?2004h[vyamang@cancun HW4]$ geturls urllist lecturelist.html
[?2004l
Warning: output file already exists.
[?2004h[vyamang@cancun HW4]$ echo $PATH
[?2004l
/usr/lib/java/apache-maven-3.8.6/bin:/usr/lib/java/apache-ant-1.10.12/bin:/usr/lib/java/apache-maven-3.8.6/bin:/usr/lib/java/apache-ant-1.10.12/bin:/data/netid/vyamang/.vscode-server/bin/252e5463d60e63238250799aef7375787f68b4ee/bin/remote-cli:/usr/lib/java/apache-maven-3.8.6/bin:/usr/lib/java/apache-ant-1.10.12/bin:/data/netid/vyamang/.local/bin:/data/netid/vyamang/bin:/usr/kerberos/sbin:/usr/kerberos/bin:/usr/lib/java/apache-maven-3.8.6/bin:/usr/lib/java/apache-ant-1.10.12/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:.
[?2004h[vyamang@cancun HW4]$ wget [7mhttps://courses.cs.washington.edu/courses/cse374/23sp/calendar/lecturelist.html[27m
[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Chttps://courses.cs.washington.edu/courses/cse374/23sp/calendar/lecturelist.html
[?2004l
--2023-05-09 19:02:29--  https://courses.cs.washington.edu/courses/cse374/23sp/calendar/lecturelist.html
Resolving courses.cs.washington.edu (courses.cs.washington.edu)... 128.208.1.193, 2607:4000:200:10::c1
Connecting to courses.cs.washington.edu (courses.cs.washington.edu)|128.208.1.193|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11623 (11K) [text/html]
Saving to: ‘lecturelist.html.2’


lecturelist.html.2           0%[                                         ]       0  --.-KB/s               
lecturelist.html.2         100%[========================================>]  11.35K  --.-KB/s    in 0s      

2023-05-09 19:02:29 (52.9 MB/s) - ‘lecturelist.html.2’ saved [11623/11623]

[?2004h[vyamang@cancun HW4]$ geturls urllist lecturelist.html
[?2004l
Warning: output file already exists.
[?2004h[vyamang@cancun HW4]$ runanalysis dataout urllist
[?2004l
Warning: file exists. Overwriting file.
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/23sp/lectures/ccode/hello.c...
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/23sp/lectures/ccode/magic.c...
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/23sp/lectures/ccode/printargs.c...
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/23sp/lectures/ccode/square1.c...
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/23sp/lectures/ccode/control.c...
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/23sp/lectures/ccode/control2.c...
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/23sp/lectures/ccode/fgets.c...
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/23sp/lectures/ccode/fopen.c...
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/23sp/lectures/ccode/dangling.c...
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/23sp/lectures/ccode/dangling.c...
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/23sp/lectures/ccode/pointeradd.c...
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/23sp/lectures/ccode/mystery.c...
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/23sp/lectures/ccode/mystery1.c...
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/23sp/lectures/ccode/mystery2.c...
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/23sp/lectures/ccode/mystery3.c...
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/23sp/lectures/ccode/mystery4.c...
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/23sp/lectures/ccode/argumentdemo.c...
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/23sp/lectures/ccode/arraydemo.c...
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/23sp/lectures/ccode/arraydynamic.c...
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/23sp/lectures/ccode/factorial_orig.c...
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/23sp/lectures/ccode/factorial_fixed.c...
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/23sp/lectures/ccode/reverse_orig.c...
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/23sp/lectures/ccode/reverse_fixed.c...
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/23sp/lectures/ccode/arrdynamicwrong.c...
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/23sp/lectures/ccode/mysterynum.c...
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/23sp/lectures/ccode/scopedemo.c...
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/23sp/lectures/ccode/point.c...
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/23sp/lectures/ccode/linkedlist_1.c...
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/23sp/lectures/ccode/linkedlist.c...
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/23sp/lectures/ccode/linkedlistclient.c...
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/23sp/lectures/ccode/debug.c...
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/23sp/lectures/ccode/twice.c...
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/23sp/lectures/ccode/main.c...
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/23sp/lectures/ccode/speak.c...
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/23sp/lectures/ccode/shout.c...
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/23sp/lectures/ccode/curve.c...
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/23sp/lectures/ccode/test.c...
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/23sp/lectures/ccode/for.c...
...successful
Performing word count measurement on https://courses.cs.washington.edu/courses/cse374/23sp/lectures/ccode/testfor.c...
...successful
[?2004h[vyamang@cancun HW4]$ scatterplot.R
[?2004l
[1] 3697
[1] 94.79487
null device 
          1 
[?2004h[vyamang@cancun HW4]$ exit
[?2004l
exit

Script done on 2023-05-09 19:04:17-07:00 [COMMAND_EXIT_CODE="0"]

## Navya Mangipudi: Statement about scatterplot trends
## Based on what is seen in scatterplot_out.jpg, there is no trend to be found
## which correlates the size of the index page (y-axis) and the url number (x-axis).
## Initially, for the first 10 point, there seemed to be a linear positive correlation. 
## For the final portion of the graph, there was no correlation between the x and y axes. 
## Points seemed to be randomly scattered. The numbers printed when running scatterplot.R 
## were [1] 3697 and [1] 94.79487. When the file scatterplot.R is opened, the meaning of these
## numbers can be seen. The first number is the sum of all the words from the c files on the
## course page. The second number is the mean of all the words from the c files on the coursepage.

